### ISSUE TITLE
new bug, jeff bezos sex mod not working? 

### ISSUE THREAD

**Issue by indigobloo** [AbhiMagic007/Turtle-go-whhahahahahahaha#3]
can someone help me with this, or is this an internal issue.
maybe my hardware is outdated?
i dont know, but it would be helpful if someone could figure this out for me.

best regards,
 @indigobloo

**Comment by AbhiMagic007** [comment]
Due to many DMCA's by Jeff Bezos we have had to disable the mod. Our legal team is currently working very hard to make Jeff our bitch.
